apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-test
  name: nginx-test
  namespace: nginx-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http-8088
    port: 8088
    protocol: TCP
    targetPort: 80
  externalIPs: 
    - 10.0.0.48
  selector:
    app: nginx-test
  type: LoadBalancer
