apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mealie
    name: mealie
    namespace: mealie
  spec:
    ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
    externalIPs:
      - 10.0.0.49
    selector:
      app: mealie
    type: LoadBalancer
kind: List
